# Site settings
baseurl = "https://quiz.sdgzone.com"
languageCode = "en-us"
title = "SDG QUIZ"

contentdir = "content"
datadir = "data"
layoutdir = "layouts"
publishdir = "public"
paginate = 10


[params]
    # Meta
    title = "SDG QUIZ"
    author = "SDSN Youth"
    description = "A website"
    keywords = "Hugo, Hugo theme"

    # Body background color
    bodybgcolor = "#ffffff"

    # Footer text
    footertext = "SDG QUIZ"
    